In [ ]:
import pandas as pd
import plotly.express as px

In [ ]:
df_2021 = pd.read_csv('/content/full (4).csv')
df_2021

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
0,2021-1,2021-01-05,1,Vente,185000.0,5080.0,NaN,CHE DE VOGELAS,0471,1370.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,2410.0,5.386107,46.327101
1,2021-1,2021-01-05,1,Vente,185000.0,5080.0,NaN,CHE DE VOGELAS,0471,1370.0,...,Maison,97.0,5.0,S,sols,NaN,NaN,2410.0,5.386107,46.327101
2,2021-2,2021-01-06,1,Vente,10.0,NaN,NaN,ROUGEMONT,B043,1290.0,...,NaN,NaN,NaN,BT,taillis simples,NaN,NaN,530.0,4.844318,46.224242
3,2021-3,2021-01-04,1,Vente,204332.0,7.0,NaN,ALL DES ECUREUILS,0276,1310.0,...,Maison,88.0,4.0,S,sols,NaN,NaN,866.0,5.157674,46.201035
4,2021-4,2021-01-06,1,Vente,320000.0,87.0,NaN,RTE DE CERTINES,0140,1250.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,1426.0,5.273214,46.156320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37272,2021-12180,2021-06-07,1,Vente,380000.0,21.0,NaN,RUE DE LA REPUBLIQUE,0550,1500.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,626.0,5.356188,45.958956
37273,2021-12180,2021-06-07,1,Vente,380000.0,21.0,NaN,RUE DE LA REPUBLIQUE,0550,1500.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,626.0,5.356188,45.958956
37274,2021-12181,2021-06-08,1,Vente,2500.0,NaN,NaN,SERRIERES DE BRIORD VILLAG,B041,1470.0,...,NaN,NaN,NaN,S,sols,NaN,NaN,143.0,5.454248,45.806220
37275,2021-12182,2021-06-07,1,Vente,110000.0,95.0,NaN,RUE DE LA VIA COLLA,0600,1360.0,...,Maison,75.0,3.0,S,sols,NaN,NaN,236.0,5.206164,45.775757
37276,2021-12183,2021-05-31,1,Vente,250000.0,23.0,NaN,RTE DU CHENAY,0020,1300.0,...,Appartement,83.0,4.0,S,sols,NaN,NaN,663.0,5.700000,NaN

In [ ]:
df_2021.shape

(37277, 40)

In [ ]:
df_2021.describe(include='all')

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
count,37277,37277,37277.000000,37277,3.701000e+04,17660.000000,1161,37188,37188,37187.000000,...,18451,10201.000000,18413.000000,28103,28103,965,965,28103.000000,36452.000000,36451.000000
unique,12183,299,NaN,5,NaN,NaN,17,8487,1414,NaN,...,4,NaN,NaN,21,21,19,19,NaN,NaN,NaN
top,2021-8082,2021-12-21,NaN,Vente,NaN,NaN,B,LE VILLAGE,B025,NaN,...,Dépendance,NaN,NaN,S,sols,FRICH,Friche,NaN,NaN,NaN
freq,152,527,NaN,34702,NaN,NaN,647,408,351,NaN,...,8141,NaN,NaN,12854,12854,276,276,NaN,NaN,NaN
mean,NaN,NaN,1.112536,NaN,3.143199e+05,860.154757,NaN,NaN,NaN,1332.918063,...,NaN,126.186550,1.878130,NaN,NaN,NaN,NaN,2067.625485,5.411789,46.144923
std,NaN,NaN,0.385407,NaN,9.294949e+05,1918.610298,NaN,NaN,NaN,212.365751,...,NaN,442.747884,2.151554,NaN,NaN,NaN,NaN,7298.468832,0.374129,0.188087
min,NaN,NaN,1.000000,NaN,1.000000e+00,1.000000,NaN,NaN,NaN,1000.000000,...,NaN,1.000000,0.000000,NaN,NaN,NaN,NaN,1.000000,4.731481,45.617666
25%,NaN,NaN,1.000000,NaN,5.400000e+04,17.000000,NaN,NaN,NaN,1170.000000,...,NaN,62.000000,0.000000,NaN,NaN,NaN,NaN,225.000000,5.153796,45.997041
50%,NaN,NaN,1.000000,NaN,1.550000e+05,81.000000,NaN,NaN,NaN,1300.000000,...,NaN,86.000000,1.000000,NaN,NaN,NaN,NaN,634.000000,5.344876,46.199114
75%,NaN,NaN,1.000000,NaN,2.950000e+05,342.250000,NaN,NaN,NaN,1480.000000,...,NaN,118.000000,4.000000,NaN,NaN,NaN,NaN,1450.000000,5.681843,46.280826
max,NaN,NaN,5.000000,NaN,2.003702e+07,9999.000000,NaN,NaN,NaN,1990.000000,...,NaN,18674.000000,18.000000,NaN,NaN,NaN,NaN,391720.000000,6.164201,46.518248

In [ ]:
df_2021['code_postal'].max()

1990.0

In [ ]:
#df_2021['date_mutation'] = pd.to_datetime(df_2021['date_mutation'], format='%Y-%m-%d').dt.date
#df_2021['valeur_fonciere'] = df_2021['valeur_fonciere'].fillna(0).astype('int64')
#df_2021['code_postal'] = df_2021['code_postal'].fillna(0).astype('int64')
#df_2021['surface_reelle_bati'] = df_2021['surface_reelle_bati'].fillna(0).astype('int64')
#df_2021['nombre_pieces_principales'] = df_2021['nombre_pieces_principales'].fillna(0).astype('int64')
#df_2021['surface_terrain'] = df_2021['surface_terrain'].fillna(0).astype('int64')

In [ ]:
#mask Maison & Appartement
#df_filter_maison_appt_2021 = df_2021[df_2021['type_local'].isin(['Maison', 'Appartement'])]
#df_filter_maison_appt_2021

NameError: name 'df_2025' is not defined

In [ ]:
# supprime les doublons ayant le même id_mutation et la même valeur_fonciere
#df_filtre_doublons_2021 = df_filter_maison_appt_2021.drop_duplicates(subset=['id_mutation', 'valeur_fonciere'])
#df_filtre_doublons_2021

In [ ]:
df_2022 = pd.read_csv('/content/full (3).csv')
df_2022

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
0,2022-1,2022-01-03,1,Vente,55000.0,13.0,NaN,RUE DE LA LIBERTE,2280,1000.0,...,Appartement,24.0,1.0,NaN,NaN,NaN,NaN,NaN,5.218712,46.198053
1,2022-2,2022-01-03,1,Vente,143000.0,NaN,NaN,CHAMP COCHET,B010,1480.0,...,NaN,NaN,NaN,S,sols,NaN,NaN,84.0,4.847876,46.000616
2,2022-2,2022-01-03,1,Vente,143000.0,NaN,NaN,CHAMP COCHET,B010,1480.0,...,NaN,NaN,NaN,S,sols,NaN,NaN,88.0,4.847927,46.000598
3,2022-2,2022-01-03,1,Vente,143000.0,98.0,NaN,RTE DE LA DOMBES,0055,1480.0,...,Appartement,140.0,3.0,NaN,NaN,NaN,NaN,NaN,4.848340,46.000631
4,2022-3,2022-01-04,1,Vente,300.0,NaN,NaN,AUX PIERRES,B031,1480.0,...,NaN,NaN,NaN,T,terres,NaN,NaN,510.0,4.747594,46.045423
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31082,2022-10720,2022-08-04,2,Echange,220.0,NaN,NaN,TRECONNAS,B109,1250.0,...,NaN,NaN,NaN,J,jardins,NaN,NaN,55.0,5.317061,46.187010
31083,2022-10721,2022-08-02,1,Vente,96860.0,227.0,NaN,RUE NEUVE,0520,1120.0,...,Appartement,49.0,2.0,S,sols,NaN,NaN,58.0,5.056672,45.850464
31084,2022-10721,2022-08-02,1,Vente,96860.0,227.0,NaN,RUE NEUVE,0520,1120.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,58.0,5.056672,45.850464
31085,2022-10722,2022-08-11,1,Vente,259000.0,729.0,NaN,RTE DE GENEVE,0186,1120.0,...,Dépendance,NaN,0.0,NaN,NaN,NaN,NaN,NaN,5.071552,45.850937
31086,2022-10722,2022-08-11,1,Vente,259000.0,729.0,NaN,RTE DE GENEVE,0186,1120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_2022.shape

NameError: name 'df_2022' is not defined

In [ ]:
df_2023 = pd.read_csv('/content/full (2).csv')
df_2023

/tmp/ipython-input-282/3581810675.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv('/content/full (2).csv')

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
0,2023-1,2023-01-05,1,Vente,1070000.0,184.0,NaN,ALL DES HETRES,0124,1630.0,...,Dépendance,NaN,0.0,NaN,NaN,NaN,NaN,NaN,6.019949,46.247458
1,2023-1,2023-01-05,1,Vente,1070000.0,159.0,NaN,ALL DES HETRES,0124,1630.0,...,Appartement,233.0,8.0,NaN,NaN,NaN,NaN,NaN,6.020204,46.247228
2,2023-1,2023-01-05,1,Vente,1070000.0,159.0,NaN,ALL DES HETRES,0124,1630.0,...,Dépendance,NaN,0.0,NaN,NaN,NaN,NaN,NaN,6.020204,46.247228
3,2023-2,2023-01-03,1,Vente,152200.0,2914.0,NaN,RTE DE PONCIN,0107,1450.0,...,Maison,64.0,3.0,S,sols,NaN,NaN,988.0,5.438273,46.129859
4,2023-3,2023-01-05,1,Vente,269000.0,427.0,T,CHE DE L'AUBEPIN,0040,1800.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,835.0,5.225844,45.853513
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31066,2023-10413,2023-09-19,1,Vente,355000.0,630.0,NaN,RTE DE PIERRE,0067,1550.0,...,Maison,94.0,4.0,VE,vergers,NaN,NaN,2012.0,5.914206,46.152461
31067,2023-10414,2023-09-21,1,Vente,NaN,NaN,NaN,GUILLERME,B471,1380.0,...,NaN,NaN,NaN,P,prés,NaN,NaN,1781.0,4.989573,46.334184
31068,2023-10414,2023-09-21,1,Vente,NaN,NaN,NaN,PRE BELICHARD,B533,1380.0,...,NaN,NaN,NaN,P,prés,NaN,NaN,20775.0,4.989055,46.334576
31069,2023-10415,2023-09-19,1,Vente,140000.0,451.0,NaN,CHE MONTCHATEL,0376,1120.0,...,Dépendance,NaN,0.0,NaN,NaN,NaN,NaN,NaN,5.062279,45.852933
31070,2023-10415,2023-09-19,1,Vente,140000.0,451.0,NaN,CHE MONTCHATEL,0376,1120.0,...,Appartement,54.0,3.0,NaN,NaN,NaN,NaN,NaN,5.062270,NaN

In [ ]:
df_2020 = pd.read_csv('/content/full (5).csv')
df_2020

/tmp/ipython-input-282/251225446.py:1: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2020 = pd.read_csv('/content/full (5).csv')

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
0,2020-1,2020-07-01,1,Vente,31234.16,NaN,NaN,SAINT JULIEN,B064,1560.0,...,NaN,NaN,NaN,AB,terrains a bâtir,NaN,NaN,1192.0,5.109255,46.403019
1,2020-2,2020-07-01,1,Vente,278000.00,NaN,NaN,A LA PEROUSE,B188,1250.0,...,NaN,NaN,NaN,BS,taillis sous futaie,NaN,NaN,10092.0,5.444577,46.252372
2,2020-2,2020-07-01,1,Vente,278000.00,NaN,NaN,A LA PEROUSE,B188,1250.0,...,NaN,NaN,NaN,L,landes,NaN,NaN,4570.0,5.444588,46.253467
3,2020-2,2020-07-01,1,Vente,278000.00,NaN,NaN,AUX COMMUNS,B079,1250.0,...,NaN,NaN,NaN,BS,taillis sous futaie,NaN,NaN,5750.0,5.442015,46.256031
4,2020-2,2020-07-01,1,Vente,278000.00,NaN,NaN,EN COMBARNAUD,B033,1250.0,...,NaN,NaN,NaN,BT,taillis simples,NaN,NaN,648170.0,5.439915,46.250795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37334,2020-14329,2020-12-17,1,Vente,89000.00,8.0,NaN,RUE DE CHATEAU THIERRY,0025,2850.0,...,Maison,80.0,4.0,S,sols,NaN,NaN,200.0,3.533712,49.088701
37335,2020-14330,2020-12-18,1,Vente,135700.00,5235.0,NaN,RUE THEODORE LIEVRAT,0055,2130.0,...,NaN,NaN,NaN,S,sols,NaN,NaN,240.0,3.637964,49.203193
37336,2020-14330,2020-12-18,1,Vente,135700.00,14.0,NaN,RUE THEODORE LIEVRAT,0055,2130.0,...,Maison,100.0,4.0,S,sols,NaN,NaN,45.0,3.637924,49.203244
37337,2020-14330,2020-12-18,1,Vente,135700.00,12.0,NaN,RUE THEODORE LIEVRAT,0055,2130.0,...,Maison,84.0,4.0,S,sols,NaN,NaN,769.0,3.637776,49.203166
37338,2020-14331,2020-12-18,1,Vente,90000.00,NaN,NaN,RUE DE REIMS,0180,2130.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#supprimer les Nan dans surface réelle - enlève aussi les doublons
df_2020 = df_2020.dropna(subset=['type_local', 'valeur_fonciere', 'surface_reelle_bati', 'nombre_pieces_principales'])
df_2020

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,num_departement
17,2020-6,2020-07-02,1,Vente,77000.0,347.0,NaN,RTE DE JALAMONDE,0220,1340.0,...,115.0,2.0,S,sols,NaN,NaN,2599.0,5.198842,46.308020,1
31,2020-8,2020-07-01,1,Vente,279000.0,1084.0,NaN,RTE DE CRANGEAT,0079,1440.0,...,122.0,5.0,S,sols,NaN,NaN,1330.0,5.215936,46.264536,1
32,2020-9,2020-07-02,1,Vente,177650.0,192.0,NaN,RUE DE MONTFLEURY,0348,1560.0,...,80.0,3.0,S,sols,NaN,NaN,260.0,5.061938,46.396034,1
36,2020-11,2020-07-03,1,Vente,169111.0,71.0,NaN,RUE BRICHEMER,0605,1000.0,...,86.0,4.0,S,sols,NaN,NaN,151.0,5.251962,46.212201,1
37,2020-12,2020-07-02,1,Vente,190000.0,5062.0,NaN,EN BOURRAVIER,B012,1250.0,...,114.0,4.0,S,sols,NaN,NaN,85.0,5.428764,46.200750,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37331,2020-14326,2020-12-15,1,Vente,160000.0,119.0,B,AV DE SOISSONS,1080,2400.0,...,70.0,3.0,NaN,NaN,NaN,NaN,NaN,3.395727,49.055645,2
37333,2020-14328,2020-12-18,2,Vente,125000.0,1.0,B,AV DE MONTMIRAIL,0070,2400.0,...,266.0,0.0,S,sols,NaN,NaN,916.0,3.407758,49.033437,2
37334,2020-14329,2020-12-17,1,Vente,89000.0,8.0,NaN,RUE DE CHATEAU THIERRY,0025,2850.0,...,80.0,4.0,S,sols,NaN,NaN,200.0,3.533712,49.088701,2
37336,2020-14330,2020-12-18,1,Vente,135700.0,14.0,NaN,RUE THEODORE LIEVRAT,0055,2130.0,...,100.0,4.0,S,sols,NaN,NaN,45.0,3.637924,49.203244,2
37337,2020-14330,2020-12-18,1,Vente,135700.0,12.0,NaN,RUE THEODORE LIEVRAT,0055,2130.0,...,84.0,4.0,S,sols,NaN,NaN,769.0,3.637776,49.203166,2

In [ ]:
# group by dept puis type_local, SUM surface_relle_bati, SUM valeur_fonciere, prix_m2
df_2020['num_departement'] = (df_2020['code_commune']/1000).astype(int64)
df_dept_2020 = df_2020.groupby(['num_departement', 'type_local']).agg(
    SUM_surface_reelle_bati = ('surface_reelle_bati', 'sum'),
    SUM_valeur_fonciere = ('valeur_fonciere', 'sum')
).reset_index()
df_dept_2020['prix_m2'] = (df_dept_2020['SUM_valeur_fonciere'] / df_dept_2020['SUM_surface_reelle_bati']).astype(int64)
df_dept_2020

/tmp/ipython-input-282/3020826172.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['num_departement'] = (df_2020['code_commune']/1000).astype(int64)

,num_departement,type_local,SUM_surface_reelle_bati,SUM_valeur_fonciere,prix_m2
0,1,Appartement,192607.0,3.125781e+09,16228
1,1,Local industriel. commercial ou assimilé,223393.0,2.268756e+08,1015
2,1,Maison,471423.0,1.164123e+09,2469
3,2,Appartement,52255.0,2.443531e+08,4676
4,2,Local industriel. commercial ou assimilé,296124.0,1.141751e+08,385
5,2,Maison,445682.0,5.597702e+08,1255

In [ ]:
df_2024 = pd.read_csv('/content/full (1).csv')
df_2024

/tmp/ipython-input-282/660537074.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2024 = pd.read_csv('/content/full (1).csv')

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
0,2024-1,2024-01-02,1,Vente,346.5,NaN,NaN,LE DELIVRE,B020,1230.0,...,NaN,NaN,NaN,P,prés,NaN,NaN,99.0,5.530952,45.952439
1,2024-2,2024-01-03,2,Vente,10000.0,NaN,NaN,CHEVRY DESSOUS,B007,1170.0,...,NaN,NaN,NaN,S,sols,NaN,NaN,115.0,6.043339,46.282256
2,2024-3,2024-01-08,1,Vente,249000.0,NaN,NaN,PIN HAMEAU,B086,1290.0,...,NaN,NaN,NaN,S,sols,NaN,NaN,497.0,4.911143,46.247235
3,2024-4,2024-01-03,1,Vente,329500.0,29.0,NaN,PL DU JURA,0500,1170.0,...,Appartement,89.0,4.0,NaN,NaN,NaN,NaN,NaN,6.058695,46.332212
4,2024-4,2024-01-03,1,Vente,329500.0,9001.0,NaN,PL DU JURA,0500,1170.0,...,Dépendance,NaN,0.0,NaN,NaN,NaN,NaN,NaN,6.058695,46.332212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37378,2024-12104,2024-12-17,1,Vente,NaN,NaN,NaN,CREUX DU LAC,B074,1410.0,...,NaN,NaN,NaN,T,terres,NaN,NaN,470.0,5.891740,46.240292
37379,2024-12104,2024-12-17,1,Vente,NaN,NaN,NaN,CREUX DU LAC,B074,1410.0,...,NaN,NaN,NaN,T,terres,NaN,NaN,559.0,5.892065,46.240661
37380,2024-12104,2024-12-17,1,Vente,NaN,NaN,NaN,LA RIVIERE,B179,1410.0,...,NaN,NaN,NaN,L,landes,NaN,NaN,2230.0,5.894278,46.241539
37381,2024-12104,2024-12-17,1,Vente,NaN,NaN,NaN,LA RIVIERE,B179,1410.0,...,NaN,NaN,NaN,L,landes,NaN,NaN,3950.0,5.891896,46.239215
37382,2024-12104,2024-12-17,1,Vente,NaN,NaN,NaN,LA RIVIERE,B179,1410.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_2025 = pd.read_csv('/content/full.csv')
df_2025

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
0,2025-1,2025-01-07,1,Vente,468000.0,NaN,NaN,FARGES,B078,1550.0,...,NaN,NaN,NaN,J,jardins,NaN,NaN,78.0,5.907229,46.170923
1,2025-1,2025-01-07,1,Vente,468000.0,454.0,NaN,RUE DE LA REPUBLIQUE,0090,1550.0,...,Maison,111.0,5.0,S,sols,NaN,NaN,133.0,5.907186,46.170782
2,2025-1,2025-01-07,1,Vente,468000.0,454.0,NaN,RUE DE LA REPUBLIQUE,0090,1550.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,133.0,5.907186,46.170782
3,2025-2,2025-01-06,1,Vente,180000.0,NaN,NaN,LE VILLAGE,B158,1200.0,...,NaN,NaN,NaN,S,sols,NaN,NaN,46.0,5.801623,46.164573
4,2025-2,2025-01-06,1,Vente,180000.0,NaN,NaN,LE VILLAGE,B158,1200.0,...,NaN,NaN,NaN,J,jardins,NaN,NaN,17.0,5.801676,46.164610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24877,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,58.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913
24878,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,58.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913
24879,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,44.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913
24880,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,63.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913
24881,2025-8155,2025-04-25,1,Vente,108900.0,22.0,NaN,RUE DE L AMITIE,00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_total = pd.concat([df_2020, df_2021, df_2022, df_2023, df_2024, df_2025], ignore_index=True)
df_total

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
0,2020-1,2020-07-01,1,Vente,31234.16,NaN,NaN,SAINT JULIEN,B064,1560.0,...,NaN,NaN,NaN,AB,terrains a bâtir,NaN,NaN,1192.0,5.109255,46.403019
1,2020-2,2020-07-01,1,Vente,278000.00,NaN,NaN,A LA PEROUSE,B188,1250.0,...,NaN,NaN,NaN,BS,taillis sous futaie,NaN,NaN,10092.0,5.444577,46.252372
2,2020-2,2020-07-01,1,Vente,278000.00,NaN,NaN,A LA PEROUSE,B188,1250.0,...,NaN,NaN,NaN,L,landes,NaN,NaN,4570.0,5.444588,46.253467
3,2020-2,2020-07-01,1,Vente,278000.00,NaN,NaN,AUX COMMUNS,B079,1250.0,...,NaN,NaN,NaN,BS,taillis sous futaie,NaN,NaN,5750.0,5.442015,46.256031
4,2020-2,2020-07-01,1,Vente,278000.00,NaN,NaN,EN COMBARNAUD,B033,1250.0,...,NaN,NaN,NaN,BT,taillis simples,NaN,NaN,648170.0,5.439915,46.250795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192823,2025-8154,2025-04-24,1,Vente,300000.00,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,58.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913
192824,2025-8154,2025-04-24,1,Vente,300000.00,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,58.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913
192825,2025-8154,2025-04-24,1,Vente,300000.00,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,44.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913
192826,2025-8154,2025-04-24,1,Vente,300000.00,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,63.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913
192827,2025-8155,2025-04-25,1,Vente,108900.00,22.0,NaN,RUE DE L AMITIE,00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_total['date_mutation'] = pd.to_datetime(df_total['date_mutation'], format='%Y-%m-%d').dt.date
df_total['valeur_fonciere'] = df_total['valeur_fonciere'].fillna(0).astype('int64')
df_total['code_postal'] = df_total['code_postal'].fillna(0).astype('int64')
df_total['num_departement'] = (df_total['code_postal']/1000).astype('int64')
df_total['surface_reelle_bati'] = df_total['surface_reelle_bati'].fillna(0).astype('int64')
df_total['nombre_pieces_principales'] = df_total['nombre_pieces_principales'].fillna(0).astype('int64')
df_total['surface_terrain'] = df_total['surface_terrain'].fillna(0).astype('int64')

In [ ]:
#supprimer les Nan dans surface réelle - enlève aussi les doublons
df_total = df_total.dropna(subset=['type_local', 'valeur_fonciere', 'surface_reelle_bati', 'nombre_pieces_principales'])
df_total

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
17,2020-6,2020-07-02,1,Vente,77000.0,347.0,NaN,RTE DE JALAMONDE,0220,1340.0,...,Maison,115.0,2.0,S,sols,NaN,NaN,2599.0,5.198842,46.308020
31,2020-8,2020-07-01,1,Vente,279000.0,1084.0,NaN,RTE DE CRANGEAT,0079,1440.0,...,Maison,122.0,5.0,S,sols,NaN,NaN,1330.0,5.215936,46.264536
32,2020-9,2020-07-02,1,Vente,177650.0,192.0,NaN,RUE DE MONTFLEURY,0348,1560.0,...,Maison,80.0,3.0,S,sols,NaN,NaN,260.0,5.061938,46.396034
36,2020-11,2020-07-03,1,Vente,169111.0,71.0,NaN,RUE BRICHEMER,0605,1000.0,...,Maison,86.0,4.0,S,sols,NaN,NaN,151.0,5.251962,46.212201
37,2020-12,2020-07-02,1,Vente,190000.0,5062.0,NaN,EN BOURRAVIER,B012,1250.0,...,Maison,114.0,4.0,S,sols,NaN,NaN,85.0,5.428764,46.200750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192822,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,33.0,1.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913
192823,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,58.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913
192824,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,58.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913
192825,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,44.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913
192826,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,Appartement,63.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913

In [ ]:
# garder les colonnes (id_mutation, date_mutation, nature_mutation, valeur_fonciere, adresse_numero, adresse_nom_voie,
# code_postal, code-commune, nom_commune, code-departement, nombre_lots, surface_reelle_bati,
# nombre_pieces_principales, surface_terrain, longitude (WGS-84), latitude(WGS-84))
df_filre_doublons = df_total.drop_duplicates(subset=['id_mutation', 'valeur_fonciere'])
df_grouped = df_filre_doublons.groupby('id_mutation').agg(
    date_mutation=('date_mutation', 'first'),
    nature_mutation=('nature_mutation', 'first'),
    valeur_fonciere=('valeur_fonciere', 'first'),
    code_postal=('code_postal', 'first'),
    code_commune=('code_commune', 'first'),
    commune=('nom_commune', 'first'),
    departement=('code_departement', 'first'),
    nb_lots=('nombre_lots', 'first'),
    surface_batie=('surface_reelle_bati', 'first'),
    nb_pieces=('nombre_pieces_principales', 'first'),
    surface_terrain=('surface_terrain', 'sum'),
    longitude=('longitude', 'first'),
    latitude=('latitude', 'first')
).reset_index()
df_grouped

In [ ]:
#df_total['num_departement'] = (df_total['code_postal']/1000).astype('int64')
#df_total

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,num_departement
17,2020-6,2020-07-02,1,Vente,77000.0,347.0,NaN,RTE DE JALAMONDE,0220,1340.0,...,115.0,2.0,S,sols,NaN,NaN,2599.0,5.198842,46.308020,1
31,2020-8,2020-07-01,1,Vente,279000.0,1084.0,NaN,RTE DE CRANGEAT,0079,1440.0,...,122.0,5.0,S,sols,NaN,NaN,1330.0,5.215936,46.264536,1
32,2020-9,2020-07-02,1,Vente,177650.0,192.0,NaN,RUE DE MONTFLEURY,0348,1560.0,...,80.0,3.0,S,sols,NaN,NaN,260.0,5.061938,46.396034,1
36,2020-11,2020-07-03,1,Vente,169111.0,71.0,NaN,RUE BRICHEMER,0605,1000.0,...,86.0,4.0,S,sols,NaN,NaN,151.0,5.251962,46.212201,1
37,2020-12,2020-07-02,1,Vente,190000.0,5062.0,NaN,EN BOURRAVIER,B012,1250.0,...,114.0,4.0,S,sols,NaN,NaN,85.0,5.428764,46.200750,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192822,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,33.0,1.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913,2
192823,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,58.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913,2
192824,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,58.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913,2
192825,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,44.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913,2
192826,2025-8154,2025-04-24,1,Vente,300000.0,14.0,NaN,RUE ARNAUD BISSON,0340,2100.0,...,63.0,2.0,NaN,NaN,NaN,NaN,NaN,3.281948,49.846913,2

Warning: Total number of columns (41) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (54851) exceeds max_rows (20000). Limiting to first (20000) rows.
Warning: Total number of columns (41) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (54851) exceeds max_rows (20000). Limiting to first (20000) rows.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:
df_total['num_departement'].max()

2

In [ ]:
#mask Maison & Appartement
df_filter_maison_appt_total = df_total[df_total['type_local'].isin(['Maison', 'Appartement'])]
df_filter_maison_appt_total

In [ ]:
# group by dept puis type_local, mean surface_relle_bati, mean valeur_fonciere,
df_agg_dept = df_total.groupby(['num_departement','type_local']).agg(
    SUM_valeur_fonciere = ('valeur_fonciere', 'sum'),
    SUM_bati = ('surface_reelle_bati', 'sum')
).reset_index()
df_agg_dept

,num_departement,type_local,SUM_valeur_fonciere,SUM_bati
0,1,Appartement,8.986513e+09,1181782.0
1,1,Local industriel. commercial ou assimilé,2.253253e+09,2275087.0
2,1,Maison,7.814247e+09,2782274.0
3,2,Appartement,2.972382e+08,73656.0
4,2,Local industriel. commercial ou assimilé,1.660776e+08,432681.0
5,2,Maison,8.029215e+08,628878.0

In [ ]:
from numpy import int64
#df_agg_dept['SUM_valeur_fonciere'] = df_agg_dept/
df_agg_dept['SUM_bati'].astype(int64)
df_agg_dept['prix_m2'] = (df_agg_dept['SUM_valeur_fonciere'] / df_agg_dept['SUM_bati']).astype(int64)
df_agg_dept

,num_departement,type_local,SUM_valeur_fonciere,SUM_bati,prix_m2
0,1,Appartement,8.986513e+09,1181782.0,7604
1,1,Local industriel. commercial ou assimilé,2.253253e+09,2275087.0,990
2,1,Maison,7.814247e+09,2782274.0,2808
3,2,Appartement,2.972382e+08,73656.0,4035
4,2,Local industriel. commercial ou assimilé,1.660776e+08,432681.0,383
5,2,Maison,8.029215e+08,628878.0,1276